### ISSUE TITLE
Upgrade servers to Ubuntu 22.04

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#659]
This is a tracking bug for upgrading servers to Ubuntu 22.04 over the next few months:

* [x] albi.openstreetmap.org
* [x] angor.openstreetmap.org
* [x] ascalon.openstreetmap.org
* [x] balerion.openstreetmap.org
* [x] bowser.openstreetmap.org
* [x] clifford.openstreetmap.org
* [x] culebre.openstreetmap.org
* [x] draco.openstreetmap.org
* [x] drogon.openstreetmap.org
* [x] dulcy.openstreetmap.org
* [x] eddie.openstreetmap.org
* [x] errol.openstreetmap.org
* [x] eustace.openstreetmap.org
* [x] fafnir.openstreetmap.org
* [x] firnen.openstreetmap.org
* [x] gorwen.openstreetmap.org
* [x] grindtooth.openstreetmap.org
* [x] grisu.openstreetmap.org
* [x] horntail.openstreetmap.org
* [x] idris.openstreetmap.org
* [x] ironbelly.openstreetmap.org
* [x] jakelong.openstreetmap.org
* [x] karm.openstreetmap.org
* [x] katla.openstreetmap.org
* [x] kessie.openstreetmap.org
* [x] konqi.openstreetmap.org
* [x] lockheed.openstreetmap.org
* [x] longma.openstreetmap.org
* [x] meraxes.openstreetmap.org
* [x] naga.openstreetmap.org
* [x] necrosan.openstreetmap.org
* [x] nepomuk.openstreetmap.org
* [x] nidhogg.openstreetmap.org
* [x] noquiklos.openstreetmap.org
* [x] norbert.openstreetmap.org
* [x] odin.openstreetmap.org
* [x] pummelzacken.openstreetmap.org
* [x] pyrene.openstreetmap.org
* [x] rhaegal.openstreetmap.org
* [ ] ridley.openstreetmap.org (Blocked by #807, server to be scrapped afterwards through #770)
* [x] sarel.openstreetmap.org
* [x] scorch.openstreetmap.org
* [ ] shenron.openstreetmap.org (Blocked by #149 and #840)
* [x] snap-01.openstreetmap.org
* [x] snap-02.openstreetmap.org
* [x] snap-03.openstreetmap.org
* [x] spike-01.openstreetmap.org
* [x] spike-02.openstreetmap.org
* [x] spike-03.openstreetmap.org
* [x] spike-04.openstreetmap.org
* [x] spike-05.openstreetmap.org
* [x] spike-06.openstreetmap.org
* [x] spike-07.openstreetmap.org
* [x] spike-08.openstreetmap.org
* [x] stormfly-03.openstreetmap.org
* [x] stormfly-04.openstreetmap.org
* [x] tabaluga.openstreetmap.org
* [x] thorn-02.openstreetmap.org
* [x] thorn-03.openstreetmap.org
* [x] thorn-04.openstreetmap.org
* [x] thorn-05.openstreetmap.org
* [x] urmel.openstreetmap.org
* [x] viserion.openstreetmap.org
* [x] ysera.openstreetmap.org

Chef tests are already passing for the many cookbooks and I'm working on the outstanding issues.

**Comment by pnorman** [comment]
The remaining machines are the wiki server, which is blocked for PHP version reasons, or machines that are begin retired.

**Comment by tomhughes** [comment]
And all the database servers.

**Comment by grischard** [comment]
And ridley, which runs civicrm, where php upgrades can be tricky.

**Comment by Firefishy** [comment]
All practical servers have been upgraded. ridley and shenron upgrades are blocked due to software upgrade requirements which are handled by separate tickets. Both servers will be demised once software upgraded.
